const ideas=[
{name:'沖繩苦瓜炒豆腐',ing:['豆腐','蛋','蔬菜'],c:'沖繩／日式',t:'normal',emoji:'🌺',desc:'苦瓜、島豆腐與蛋的經典家常組合，鹹香下飯又有爽脆口感。',step:'苦瓜鹽抓去苦味 → 豆腐煎香 → 加豬肉或午餐肉翻炒 → 淋蛋液與醬油完成。'},
{name:'照燒雞肉丼',ing:['雞肉','白飯'],c:'沖繩／日式',t:'quick',emoji:'🍚',desc:'甜鹹照燒醬裹住嫩雞肉，鋪在熱飯上就是可靠的一餐。',step:'雞腿煎至金黃 → 加醬油、味醂與糖收汁 → 切片鋪飯，配青菜。'},
{name:'台式三杯雞',ing:['雞肉','蔬菜'],c:'台灣',t:'normal',emoji:'🌿',desc:'麻油、醬油和米酒收成濃亮醬汁，九層塔最後下鍋最香。',step:'薑片麻油煸香 → 雞肉炒至上色 → 加三杯醬料燜煮 → 九層塔拌勻。'},
{name:'番茄炒蛋',ing:['蛋','蔬菜'],c:'台灣',t:'quick',emoji:'🍅',desc:'酸甜柔軟的家常菜，十分鐘上桌，拌飯或配麵都適合。',step:'蛋炒至半熟盛起 → 番茄炒出汁並調味 → 蛋回鍋輕拌。'},
{name:'港式豉油王炒麵',ing:['蔬菜','麵'],c:'香港／廣東',t:'quick',emoji:'🥢',desc:'焦香麵條配豆芽與韭黃，簡單但很有鑊氣。',step:'麵條煎香 → 大火炒豆芽韭黃 → 加老抽、生抽與糖快速拌勻。'},
{name:'滑蛋蝦仁燴飯',ing:['魚／海鮮','蛋','白飯'],c:'香港／廣東',t:'normal',emoji:'🍤',desc:'柔滑蛋花和鮮甜蝦仁，醬汁淋在白飯上非常療癒。',step:'蝦仁炒熟 → 高湯勾薄芡 → 緩緩淋入蛋液 → 熄火滑散後澆飯。'},
{name:'韓式辣炒豬肉',ing:['豬肉','蔬菜'],c:'韓式',t:'normal',emoji:'🌶️',desc:'韓式辣醬的甜辣滋味，搭洋蔥與高麗菜一次炒完。',step:'豬肉用辣醬、醬油、糖醃製 → 與洋蔥高麗菜大火炒熟 → 撒芝麻。'},
{name:'韓式豆腐鍋',ing:['豆腐','蛋','蔬菜'],c:'韓式',t:'normal',emoji:'🍲',desc:'一鍋暖呼呼的微辣湯料理，冰箱剩菜也能一起加入。',step:'炒香泡菜與蒜 → 加高湯煮滾 → 放豆腐與配料 → 最後打一顆蛋。'},
{name:'泰式打拋豬',ing:['豬肉','蛋','白飯'],c:'泰式',t:'quick',emoji:'🍳',desc:'魚露、辣椒和羅勒帶來醒胃香氣，再加一顆酥邊煎蛋。',step:'蒜與辣椒爆香 → 豬絞肉炒散 → 魚露、糖調味 → 加羅勒，配煎蛋。'},
{name:'泰式檸檬魚',ing:['魚／海鮮','蔬菜'],c:'泰式',t:'normal',emoji:'🐟',desc:'酸辣清爽的蒸魚，檸檬、蒜與魚露讓鮮味更明亮。',step:'魚蒸熟 → 混合檸檬汁、魚露、糖、蒜與辣椒 → 趁熱淋上。'},
{name:'蒜香奶油海鮮義大利麵',ing:['魚／海鮮','麵'],c:'義式／西式',t:'normal',emoji:'🍝',desc:'蒜香奶油包裹麵條與海鮮，像餐廳料理但做法很直接。',step:'煮麵 → 蒜末奶油炒海鮮 → 加煮麵水乳化 → 拌麵與黑胡椒。'},
{name:'香草烤蔬菜雞肉',ing:['雞肉','蔬菜'],c:'義式／西式',t:'slow',emoji:'🍗',desc:'全部鋪上烤盤就能休息，適合不想一直顧爐火的晚上。',step:'雞肉蔬菜拌橄欖油、鹽與香草 → 200°C 烤約 35 分鐘至金黃。'},
{name:'日式牛肉壽喜煮',ing:['牛肉','豆腐','蔬菜'],c:'沖繩／日式',t:'normal',emoji:'🥘',desc:'甜鹹湯汁煮牛肉、豆腐與蔬菜，最後剩汁還能煮烏龍麵。',step:'醬油、味醂、糖與水煮滾 → 放蔬菜豆腐 → 牛肉最後涮熟。'},
{name:'台式紅燒牛肉',ing:['牛肉','蔬菜'],c:'台灣',t:'slow',emoji:'🥩',desc:'番茄豆瓣的厚實湯底，適合週末慢燉並多做幾餐。',step:'牛肉汆燙 → 薑蒜豆瓣炒香 → 加番茄醬油與水 → 小火燉至軟嫩。'},
{name:'廣東蒸水蛋',ing:['蛋'],c:'香港／廣東',t:'quick',emoji:'🥚',desc:'像布丁一樣細滑的蒸蛋，可放肉末、蝦仁或只淋豉油。',step:'蛋與溫水 1:1.5 混合過篩 → 蓋盤小火蒸 10 分鐘 → 淋豉油。'},
{name:'剩飯蔬菜蛋炒飯',ing:['白飯','蛋','蔬菜'],c:'台灣',t:'quick',emoji:'♻️',desc:'把冷飯與零碎蔬菜變成粒粒分明的快速晚餐。',step:'蛋炒散 → 加切碎剩菜大火翻炒 → 加冷飯炒鬆 → 醬油與胡椒調味。'}];
const pantry=['雞肉','豬肉','牛肉','魚／海鮮','豆腐','蛋','蔬菜','白飯','麵'];let mode='normal',current=null;const state=load();function load(){try{return JSON.parse(localStorage.getItem('kaka-cooking-v2'))||{favorites:[],shopping:[]}}catch{return{favorites:[],shopping:[]}}}function save(){localStorage.setItem('kaka-cooking-v2',JSON.stringify(state))}document.querySelector('#ingredients').innerHTML=pantry.map(x=>`<label><input type="checkbox" value="${x}"><span>${x}</span></label>`).join('');function selected(){return [...document.querySelectorAll('#ingredients input:checked')].map(x=>x.value)}
function generate(random=false){const chosen=random?[]:selected(),c=random?'any':document.querySelector('#cuisine').value,t=random?'any':document.querySelector('#time').value;let pool=ideas.filter(x=>(c==='any'||x.c===c)&&(t==='any'||x.t===t));if(!pool.length)pool=ideas;const score=x=>x.ing.filter(i=>chosen.includes(i)).length;if(chosen.length){const best=Math.max(...pool.map(score));pool=pool.filter(x=>score(x)===(mode==='leftover'?best:Math.max(1,best)))}if(!pool.length)pool=ideas;current=pool[Math.floor(Math.random()*pool.length)];renderIdea(current,chosen)}
function renderIdea(x,chosen){const time={quick:'約 15 分鐘',normal:'約 30 分鐘',slow:'慢燉／烤料理'}[x.t],used=x.ing.filter(i=>chosen.includes(i)).length,missing=x.ing.filter(i=>!chosen.includes(i));const box=document.querySelector('#idea');box.innerHTML=`<div class="plate">${x.emoji}</div><p class="kicker">${mode==='leftover'?`利用 ${used} 種現有食材`:'今晚的靈感'}</p><h2>${x.name}</h2><p class="desc">${x.desc}</p><div class="meta"><span>🥬 ${x.ing.join('・')}</span><span>🌏 ${x.c}</span><span>⏱ ${time}</span></div><div class="steps"><strong>簡單做法：</strong>${x.step}</div><div class="idea-actions"><button id="favorite">${state.favorites.includes(x.name)?'♥ 已收藏':'♡ 收藏'}</button><button id="add-missing">＋ 缺的放進採買清單${missing.length?` (${missing.length})`:''}</button></div>`;box.classList.remove('fresh');void box.offsetWidth;box.classList.add('fresh');document.querySelector('#favorite').onclick=toggleFavorite;document.querySelector('#add-missing').onclick=()=>{missing.forEach(addShopping);renderSaved()}}
function toggleFavorite(){if(!current)return;const i=state.favorites.indexOf(current.name);i<0?state.favorites.push(current.name):state.favorites.splice(i,1);save();renderSaved();renderIdea(current,selected())}function addShopping(item){if(item&&!state.shopping.includes(item))state.shopping.push(item);save()}function renderSaved(){const f=document.querySelector('#favorites'),s=document.querySelector('#shopping');f.innerHTML=state.favorites.length?state.favorites.map(x=>`<span>${x}<button data-fav="${x}">×</button></span>`).join(''):'還沒有收藏，遇到喜歡的料理就按愛心。';s.innerHTML=state.shopping.length?state.shopping.map(x=>`<span>${x}<button data-shop="${x}">✓</button></span>`).join(''):'清單是空的。'}
document.querySelector('.mode-tabs').onclick=e=>{const b=e.target.closest('[data-mode]');if(b){mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));document.querySelector('#generate').textContent=mode==='leftover'?'♻️ 拯救我的剩菜':'✨ 給我一道菜'}};document.querySelector('#generate').onclick=()=>generate(false);document.querySelector('#surprise').onclick=()=>generate(true);document.querySelector('#shopping-form').onsubmit=e=>{e.preventDefault();const input=document.querySelector('#shopping-input'),value=input.value.trim();addShopping(value);input.value='';renderSaved()};document.querySelector('#favorites').onclick=e=>{const b=e.target.closest('[data-fav]');if(b){state.favorites=state.favorites.filter(x=>x!==b.dataset.fav);save();renderSaved()}};document.querySelector('#shopping').onclick=e=>{const b=e.target.closest('[data-shop]');if(b){state.shopping=state.shopping.filter(x=>x!==b.dataset.shop);save();renderSaved()}};document.querySelectorAll('[data-clear]').forEach(b=>b.onclick=()=>{state[b.dataset.clear]=[];save();renderSaved()});renderSaved();
